baseURL = "https://mcclatchy.github.io/saratoga/"
languageCode = "en-us"
title = "McClatchy Redesign"

canonifyURLs = true
disableKinds = ["RSS", "sitemap", "robotsTXT", "404", "taxonomy", "taxonomyTerm"]
ignoreFiles = ["cs2hugo"]
pluralizeListTitles = false

[[menu.main]]
  name = "HOME"
  url = "/"
  weight = 1
[[menu.main]]
  name = "NEWS"
  url = "/news/"
  weight = 2
[[menu.main]]
  name = "SPORTS"
  url = "/sports/"
  weight = 3
[[menu.main]]
  name = "FOOD"
  url = "/food/"
  weight = 4
[[menu.main]]
  name = "OPINION"
  url = "/opinion/"
  weight = 5
